name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project with environment variables
      - name: Build the project
        env:
          REACT_APP_GROQ_API_KEY: ${{ secrets.REACT_APP_GROQ_API_KEY }}  # Accessing the API key stored in GitHub secrets
        run: npm run build

      # Step 5: Deploy to GitHub Pages using gh-pages
      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          npm run deploy
