name: Deploy React App to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch to deploy"
        required: true
        default: "master"
        type: choice
        options:
          - master
          - develop
          - feature-branch

env:
  REACT_APP_GROQ_API_KEY: ${{ secrets.REACT_APP_GROQ_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the selected branch
      - name: Check out the selected branch
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        env:
          REACT_APP_GROQ_API_KEY: ${{ secrets.REACT_APP_GROQ_API_KEY }}
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
